unique_ids:
  assets:
    standard-page.html: W65V55P6NI7SAHIP2T7NNSX3WVE6GRDZ
    theme.css: OLMLWKDNPIIWITBZZ6DBPQOYXSIZAEHF
  forms:
    Form1: XIWKPK7JIW6B6DUE7ARDGEOQJAS27XPW
  modules: {}
  scripts: {}
  server_modules: {}
